#!/bin/sh

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

	# install homebrew if it's missing
	if [ ! -f /opt/homebrew/bin/brew ]; then
		echo "Installing homebrew"
		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	fi

	# install brew packages
	if [ -f "$HOME/.Brewfile" ]; then
		echo "Updating homebrew bundle"
		brew bundle --global
	fi

fi

# install tmux plugins manager
if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
	git clone --depth 1 https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
fi

# install neovim plugins manager
if [ ! -d "$HOME/.local/share/nvim/site/pack/packer/start/packer.nvim" ]; then
	git clone --depth 1 https://github.com/wbthomason/packer.nvim "$HOME/.local/share/nvim/site/pack/packer/start/packer.nvim"
fi
