theme = "onedark"

[editor]
bufferline = "multiple"
color-modes = true
idle-timeout = 0
line-number = "relative"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false
max-depth = 5

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
