[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt", args = ["--indent", "2"] }

[[language]]
name = "hcl"
roots = [".terraform.lock.hcl", ".git"]

[[language]]
name = "helm"
scope = "source.helm"
injection-regex = "^helm$"
file-types = ["helm.yaml", "templates/*.yaml"]
roots = ["Chart.yaml"]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
language-server = { command = "helm_ls", args = ["serve"] }
grammar = "helm"

[[grammar]]
name = "helm"
source = { git = "https://github.com/dannylongeuay/tree-sitter-go-template", rev = "395a33e08e69f4155156f0b90138a6c86764c979" }
